### ISSUE TITLE
GPlinks not working

### ISSUE THREAD

**Issue by askfriends** [aayush2718/Auto-Link-Bypasser#3]
gplink bypass doesnt work, got error 

`python bypass.py https://gplinks.co/SVceypU
Traceback (most recent call last):
  File "C:\Users\LAPTOP\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\requests\models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2544.0_x64__qbz5n2kfra8p0\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2544.0_x64__qbz5n2kfra8p0\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2544.0_x64__qbz5n2kfra8p0\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\LAPTOP\Documents\Auto-Link-Bypasser\bypass.py", line 269, in <module>
    print(gplinks_bypass(url))
  File "C:\Users\LAPTOP\Documents\Auto-Link-Bypasser\bypass.py", line 68, in gplinks_bypass
    res = client.post(final_url, data=data, headers=h).json()
  File "C:\Users\LAPTOP\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

**Comment by archelaus** [comment]
GPlinks changed their obfuscation quite a while ago. Will take a look at if I can reverse the new obfuscation somehow. Leaving this issue open in case anyone else stumbles across this repo/issue

**Comment by askfriends** [comment]
> GPlinks changed their obfuscation quite a while ago. Will take a look at if I can reverse the new obfuscation somehow. Leaving this issue open in case anyone else stumbles across this repo/issue

yeah that would be great, BTW gplink bypass isnt working in any bypasser script or addon i have came across so far.

**Comment by askfriends** [comment]
any update so far?
